name: ptb
hf_id: ptb_text_only
hf_config: penn_treebank
split_ratios:
  train: 0.8
  val: 0.1
  test: 0.1
max_seq_len: 256
batch_size: 16
num_workers: 2
tokenizer: gpt2
streaming: false
domain: general
text_column: sentence
